"""Generate the full evaluation: 10 prompts x 9 contexts x 6 arms.

Supports: every compliance result in the paper (CCR table, violations per
document, per-code counts, flag and round-trip rates, false-negative rate),
since all of them score the documents this script produces. Makes live model
calls (draft generation, the baselines, parsing and Detect regeneration).

Configuration is verified by phase2_generation_lib.assert_config(): frozen
libraries (LIB-FAITHFUL-P-v2 for CP-GTR and CP-GTR-Detect, LIB-FULL for
CP-GTR-Ungated), the template-correction file, the codebook, the prompt file,
PARSE_MAX_TOKENS=8192 and the production parser configuration (no negative
example). It refuses to run on any hash or count mismatch.

Resumable: pairs already present in analysis/phase2_generation_pairs.json are
skipped. The released file was seeded with the P1-P3 pairs produced by
phase2_generation_run_AD.py (27 pairs, same configuration), so only P4-P10
were generated by this script; with no existing pairs file it generates all
90 pairs. It also generates five practice documents (PRACTICE-1 in three
contexts, PRACTICE-2 in two), stored separately and never scored or placed on
the annotation sheet.

Run (from the repository root, after the library and corrections exist):
    python analysis/phase2_generation_run.py
Order: before phase2_taskZ_annotation_sheet.py, phase2_taskY_coverage.py and
all phase2_final_results*.py scripts.

Inputs : docs/phase2_prompts_v1.md, schema/codebook_v2.json,
         analysis/phase2_library.json, analysis/realization_templates_corrections.json,
         cache/canonical_extraction_cache.jsonl; the LLM provider (cpgtr/llm.py).
Outputs: analysis/phase2_generation_pairs.json (90 pairs, six-arm text + _meta),
         analysis/phase2_generation_practice.json,
         analysis/phase2_generation.json (flat per-document provenance:
         540 evaluation rows and 30 practice rows).
"""
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from cpgtr.admit import CONTEXTS
from cpgtr.baselines import draft_unconstrained, draft_fewshot, critique_revise_rlaif
from run_e2e import flag_violations, cpgtr_detect_repair
from analysis.phase2_harness import run_six_arms_for_pair, normalize_text, text_hash
from analysis.phase2_generation_lib import load_prompts, assert_config

PROMPTS_THIS_RUN = [f"P{i}" for i in range(1, 11)]   # all 10 eval prompts

# PRACTICE-1 in three contexts, PRACTICE-2 in two. Any split works, since the
# practice documents are used only for annotator training.
PRACTICE_PLAN = [
    ("PRACTICE-1", (9, "US")), ("PRACTICE-1", (15, "EU")), ("PRACTICE-1", (21, "UK")),
    ("PRACTICE-2", (9, "EU")), ("PRACTICE-2", (21, "US")),
]

PAIRS_PATH = REPO_ROOT / "analysis" / "phase2_generation_pairs.json"
PRACTICE_PATH = REPO_ROOT / "analysis" / "phase2_generation_practice.json"
DOCS_PATH = REPO_ROOT / "analysis" / "phase2_generation.json"

print("Asserting configuration (refuses to run on any hash/count mismatch)...")
cfg = assert_config()
for k, v in cfg["config_summary"].items():
    print(f"  {k}: {v}")
print("Configuration asserted OK.\n")

eval_prompts, practice_prompts = load_prompts()

pairs = json.loads(PAIRS_PATH.read_text(encoding="utf-8")) if PAIRS_PATH.exists() else {}
print(f"{len(pairs)} eval pairs already present (resumed).")

complete, parser = cfg["complete"], cfg["parser"]
cpgtr_cert, ungated_cert = cfg["cpgtr_cert"], cfg["ungated_cert"]

# ------------------------------------------------------------- 90 eval pairs
for prompt_id in PROMPTS_THIS_RUN:
    prompt_text = eval_prompts[prompt_id]
    pair_ids_for_prompt = [f"{prompt_id}_{A}_{J}" for (A, J) in CONTEXTS]
    if all(pid in pairs for pid in pair_ids_for_prompt):
        print(f"{prompt_id}: all 9 contexts already present, skipping.")
        continue

    print(f"=== {prompt_id}: {prompt_text[:70]}... ===")
    unconstrained_text = draft_unconstrained(complete, prompt_text)

    for i, ctx in enumerate(CONTEXTS):
        A, J = ctx
        pair_id = f"{prompt_id}_{A}_{J}"
        if pair_id in pairs:
            continue
        fewshot_text = draft_fewshot(complete, prompt_text, A, J)
        rlaif_text = critique_revise_rlaif(complete, unconstrained_text, A, J)

        result = run_six_arms_for_pair(
            complete, parser, cpgtr_cert, ungated_cert,
            unconstrained_text, fewshot_text, rlaif_text, ctx,
            flag_violations, cpgtr_detect_repair,
        )
        result["context"] = {"A": A, "J": J}
        result["prompt_id"] = prompt_id
        pairs[pair_id] = result
        print(f"  [{i+1}/9] {pair_id}: host N/E={result['_meta']['host_n_nodes']}/"
              f"{result['_meta']['host_n_edges']}  Detect={result['_meta']['CP-GTR-Detect_flagged']}  "
              f"CP-GTR={result['_meta']['CP-GTR_flagged']}  Ungated={result['_meta']['CP-GTR-Ungated_flagged']}  "
              f"host_fallback={result['_meta']['host_parse_fallback']}  "
              f"neg_drops={len(result['_meta']['host_negation_drops'])}")

        PAIRS_PATH.write_text(json.dumps(pairs, indent=2, ensure_ascii=False), encoding="utf-8")

print(f"\nWritten: {PAIRS_PATH} ({len(pairs)} pairs total)")

# --------------------------------------------------------- 5 practice documents
practice_pairs = json.loads(PRACTICE_PATH.read_text(encoding="utf-8")) if PRACTICE_PATH.exists() else {}
print(f"\n{len(practice_pairs)} practice pairs already present (resumed).")

practice_unconstrained = {}
for prompt_id, ctx in PRACTICE_PLAN:
    A, J = ctx
    pair_id = f"{prompt_id}_{A}_{J}"
    if pair_id in practice_pairs:
        continue
    if prompt_id not in practice_unconstrained:
        practice_unconstrained[prompt_id] = draft_unconstrained(complete, practice_prompts[prompt_id])
    unconstrained_text = practice_unconstrained[prompt_id]
    fewshot_text = draft_fewshot(complete, practice_prompts[prompt_id], A, J)
    rlaif_text = critique_revise_rlaif(complete, unconstrained_text, A, J)

    result = run_six_arms_for_pair(
        complete, parser, cpgtr_cert, ungated_cert,
        unconstrained_text, fewshot_text, rlaif_text, ctx,
        flag_violations, cpgtr_detect_repair,
    )
    result["context"] = {"A": A, "J": J}
    result["prompt_id"] = prompt_id
    practice_pairs[pair_id] = result
    print(f"  {pair_id}: host N/E={result['_meta']['host_n_nodes']}/{result['_meta']['host_n_edges']}")
    PRACTICE_PATH.write_text(json.dumps(practice_pairs, indent=2, ensure_ascii=False), encoding="utf-8")

print(f"Written: {PRACTICE_PATH} ({len(practice_pairs)} practice pairs)")

# --------------------------------------------------------- flatten to per-document
ARM_LIB_HASH = {
    "Unconstrained": None, "Few-Shot Prompted": None, "Constitutional AI (RLAIF)": None,
    "CP-GTR-Detect": cfg["cpgtr_rec"]["sha256"], "CP-GTR": cfg["cpgtr_rec"]["sha256"],
    "CP-GTR-Ungated": cfg["ungated_rec"]["sha256"],
}


def flatten(entry, pair_id, is_practice):
    meta = entry["_meta"]
    out = []
    for arm in ("Unconstrained", "Few-Shot Prompted", "Constitutional AI (RLAIF)",
                "CP-GTR-Detect", "CP-GTR", "CP-GTR-Ungated"):
        text = entry[arm]
        flag_status = {
            "CP-GTR-Detect": meta["CP-GTR-Detect_flagged"],
            "CP-GTR": meta["CP-GTR_flagged"],
            "CP-GTR-Ungated": meta["CP-GTR-Ungated_flagged"],
        }.get(arm)
        rules_fired = {
            "CP-GTR-Detect": meta["CP-GTR-Detect_rules_fired"],
            "CP-GTR": meta["CP-GTR_rules_fired"],
            "CP-GTR-Ungated": meta["CP-GTR-Ungated_rules_fired"],
        }.get(arm)
        round_trip_result = {
            "CP-GTR": {"passed": meta["CP-GTR_round_trip_passed"],
                       "parse_fallback": meta["CP-GTR_round_trip_parse_fallback"]},
            "CP-GTR-Ungated": {"passed": meta["CP-GTR-Ungated_round_trip_passed"],
                                "parse_fallback": meta["CP-GTR-Ungated_round_trip_parse_fallback"]},
        }.get(arm)
        provenance_verified = {
            "CP-GTR": meta["CP-GTR_provenance_verified"],
            "CP-GTR-Ungated": meta["CP-GTR-Ungated_provenance_verified"],
        }.get(arm)
        # Data completeness: the 27 pairs seeded from the first generation
        # batch (P1-P3 x 9 contexts) were produced before the per-document
        # negation-drop lists (host_negation_drops and the round-trip drop
        # lists) were stored in _meta. The negation filter was already active
        # for them, but the lists were not captured, and a fresh re-parse
        # would be a new stochastic model measurement, so they are not
        # backfilled. negation_filter_drops is therefore None (not []) for
        # those pairs, which distinguishes "not recorded" from a genuine
        # zero-drop result on the other 63 evaluation and 5 practice pairs.
        negation_drops_available = "host_negation_drops" in meta
        arm_negation_drops = None
        if negation_drops_available:
            arm_negation_drops = {
                "CP-GTR": meta["host_negation_drops"] + meta["CP-GTR_round_trip_negation_drops"],
                "CP-GTR-Ungated": meta["host_negation_drops"] + meta["CP-GTR-Ungated_round_trip_negation_drops"],
                "CP-GTR-Detect": meta["host_negation_drops"],
            }.get(arm, [])
        out.append({
            "pair_id": pair_id, "prompt_id": entry["prompt_id"], "context": entry["context"],
            "arm": arm, "is_practice": is_practice,
            "library_hash": ARM_LIB_HASH[arm], "flag_status": flag_status,
            "round_trip_result": round_trip_result, "rules_fired": rules_fired,
            "provenance_verified": provenance_verified,
            "negation_filter_drops": arm_negation_drops,
            "negation_drops_available": negation_drops_available,
            "host_parse_fallback": meta["host_parse_fallback"],
            "host_parse_attempts": meta["host_parse_attempts"],
            "host_n_nodes": meta["host_n_nodes"], "host_n_edges": meta["host_n_edges"],
            "text": text, "text_hash": text_hash(text),
        })
    return out


documents = []
for pair_id, entry in pairs.items():
    documents.extend(flatten(entry, pair_id, is_practice=False))
for pair_id, entry in practice_pairs.items():
    documents.extend(flatten(entry, pair_id, is_practice=True))

DOCS_PATH.write_text(json.dumps(documents, indent=2, ensure_ascii=False), encoding="utf-8")
print(f"\nWritten: {DOCS_PATH} ({len(documents)} documents: "
      f"{len(pairs) * 6} eval + {len(practice_pairs) * 6} practice)")
